language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "iojs"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs"

branches:
  only:
    - master

script:
  - npm run lint
  - npm test
